# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Daniel Siromani"

# A description of your site for meta tag, search engine results.
description: "Machine Learning, Software, Electronics and other projects & things which have taken my fancy"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://scriptor-jekyll.netlify.com"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Publications
    url: /publications

# The shortname for your Disqus site to enable comments.
disqus:

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "Theme modified from Scriptor by JustGoodThemes"
  has_social: false

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'

gems:
  - jekyll-scholar


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

scholar:
  style: ieee
  bibliography_template: bib2
  bibliography_list_tag: "ul"
  #bibliography_list_tag: 'div'
  #bibliography_item_tag: 'p'